### ISSUE TITLE
Failing testcase #9

### ISSUE THREAD

**Issue by lukasglandorf** [hofmannu/CLAHE3D#7]
Running CLAHE3D with GPU support fails testcase #9 with the following output:

```
ctest --rerun-failed --output-on-failure

Start 9: test_gaussfilt
1/1 Test #9: test_gaussfilt ...................Subprocess aborted***Exception:   1.38 sec
terminate called after throwing an instance of 'char const*'


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.38 sec

The following tests FAILED:
	  9 - test_gaussfilt (Subprocess aborted)
Errors while running CTest
```

Possibly related warnings that are thrown during compilation:

```
meanfilt.h:24:7: warning: direct base ‘cudaTools’ inaccessible in ‘meanfilt’ due to ambiguity [-Winaccessible-base]
   24 | class meanfilt :
      |       ^~~~~~~~
```

```
 warning: narrowing conversion of ‘(int)sett.gaussfiltsett::kernelSize[0]’ from ‘int’ to ‘long unsigned int’ [-Wnarrowing]
   75 |         gaussfilter.set_kernelSize(
      |        
```           

I downloaded and built the packaged exactly as provided in the instructions. System is an updated ARCH Linux with Nvidia 3090.

**Comment by hofmannu** [comment]
I recompiled and tested the latest version and could not reproduce the issue

Test environment:
```
OS: Arch Linux x86_64 
Kernel: 5.15.87-1-lts
CPU: Intel Xeon W-11955M (16) @ 4.900GHz 
GPU: NVIDIA RTX A2000 Mobile
```

Nevertheless, the gauss filter test was based on random numbers with a time dependent seed, so it might very well be that you had a unlucky combination. I increased the precision of the test and made it more fail safe by using a defined set of random numbers, please try again with the latest version and let me know if it still fails.

**Comment by lukasglandorf** [comment]
that fixed the problem, thanks!
